// Sous-ensemble de translations.js, réservé à Home.jsx — la seule page
// importée statiquement (non lazy) dans App.jsx, donc la seule dont les
// imports finissent dans le bundle "index" chargé par tout visiteur, même
// anonyme. translations.js (6 langues, toutes les pages) pèse ~338 Ko
// rendus — l'y importer en entier pour 23 clés forçait ce poids sur la
// toute première page publique. Toutes les autres pages continuent d'utiliser
// translations.js normalement (aucun changement, aucun risque pour elles).
// Même format/signature que t()/LANGS de translations.js — si une clé
// supplémentaire est utilisée un jour dans Home.jsx, l'ajouter ici (copier la
// ligne depuis translations.js) plutôt que de réimporter le fichier complet.

export const LANGS = [
  { code: 'fr', label: 'Français',    flag: '🇫🇷' },
  { code: 'en', label: 'English',     flag: '🇬🇧' },
  { code: 'pt', label: 'Português',   flag: '🇧🇷' },
  { code: 'es', label: 'Español',     flag: '🇪🇸' },
  { code: 'it', label: 'Italiano',    flag: '🇮🇹' },
  { code: 'de', label: 'Deutsch',     flag: '🇩🇪' },
]

const T_HOME = {
  auth_connexion_titre:       { fr: 'Connexion',                en: 'Login',                  pt: 'Iniciar sessão',        es: 'Iniciar sesión',         it: 'Accedi',                de: 'Anmelden'             },
  home_cgu:                 { fr: 'CGU',                       en: 'Terms',                  pt: 'Termos',                es: 'Términos',               it: 'Termini',               de: 'AGB'                  },
  home_commencer:           { fr: 'Commencer',                 en: 'Get started',            pt: 'Começar',               es: 'Empezar',                it: 'Inizia',                de: 'Loslegen'             },
  home_comment_marche:      { fr: 'Comment ça marche',         en: 'How it works',           pt: 'Como funciona',         es: 'Cómo funciona',          it: 'Come funziona',         de: 'So funktioniert es'   },
  home_envoyer_video:       { fr: 'Rejoindre gratuitement',    en: 'Join for free',         pt: 'Aderir gratuitamente',  es: 'Únete gratis',           it: 'Iscriviti gratis',      de: 'Kostenlos beitreten'  },
  home_etape1_desc:         { fr: 'Crée ton profil joueur en 2 minutes', en: 'Create your player profile in 2 minutes', pt: 'Cria o teu perfil de jogador em 2 minutos', es: 'Crea tu perfil de jugador en 2 minutos', it: 'Crea il tuo profilo giocatore in 2 minuti', de: 'Erstelle dein Spielerprofil in 2 Minuten' },
  home_etape1_titre:        { fr: "Tu t'inscris",              en: 'You sign up',            pt: 'Inscreves-te',          es: 'Te registras',           it: "Ti iscrivi",            de: 'Du registrierst dich' },
  home_etape2_desc:         { fr: "Rejoins ton club et ton éducateur avec un code d'équipe", en: 'Join your club and coach with a team code', pt: 'Junta-te ao teu clube e treinador com um código de equipa', es: 'Únete a tu club y entrenador con un código de equipo', it: 'Unisciti al tuo club e al tuo allenatore con un codice squadra', de: 'Tritt deinem Verein und Trainer mit einem Teamcode bei' },
  home_etape2_titre:        { fr: 'Tu te connectes',           en: 'You connect',            pt: 'Conectas-te',           es: 'Te conectas',            it: 'Ti connetti',           de: 'Du vernetzt dich'     },
  home_etape3_desc:         { fr: 'Suis tes stats, ta présence, et les retours de ton éducateur', en: 'Track your stats, attendance, and feedback from your coach', pt: 'Acompanha as tuas estatísticas, presença e o feedback do teu treinador', es: 'Sigue tus estadísticas, tu asistencia y el feedback de tu entrenador', it: 'Segui le tue statistiche, la presenza e i feedback del tuo allenatore', de: 'Verfolge deine Statistiken, Anwesenheit und das Feedback deines Trainers' },
  home_etape3_titre:        { fr: 'Tu progresses',             en: 'You improve',            pt: 'Tu progrides',          es: 'Progresas',              it: 'Migliori',              de: 'Du entwickelst dich'  },
  home_etape4_desc:         { fr: 'Partage tes moments forts et sois visible des recruteurs', en: 'Share your highlights and get visible to scouts', pt: 'Partilha os teus melhores momentos e fica visível para os recrutadores', es: 'Comparte tus mejores momentos y hazte visible para los reclutadores', it: 'Condividi i tuoi momenti migliori e fatti notare dagli osservatori', de: 'Teile deine Highlights und werde für Scouts sichtbar' },
  home_etape4_titre:        { fr: 'Tu te fais voir',           en: 'You get noticed',        pt: 'Fazes-te notar',        es: 'Te haces notar',         it: 'Ti fai notare',         de: 'Du wirst gesehen'     },
  home_financement:         { fr: 'Financement',               en: 'Funding',                pt: 'Financiamento',         es: 'Financiación',           it: 'Finanziamento',         de: 'Finanzierung'         },
  home_inscription:         { fr: 'Inscription',               en: 'Sign up',                pt: 'Registo',               es: 'Registro',               it: 'Iscrizione',            de: 'Registrierung'        },
  home_nouveau:             { fr: 'NOUVEAU',                   en: 'NEW',                    pt: 'NOVO',                  es: 'NUEVO',                  it: 'NUOVO',                 de: 'NEU'                  },
  home_offres:              { fr: 'Offres',                    en: 'Plans',                  pt: 'Planos',                es: 'Planes',                 it: 'Piani',                 de: 'Angebote'             },
  home_processus:           { fr: 'PROCESSUS',                 en: 'PROCESS',                pt: 'PROCESSO',              es: 'PROCESO',                it: 'PROCESSO',              de: 'PROZESS'              },
  home_tiktok_desc:         { fr: 'Clips courts, format vertical. Swipe entre les vidéos et découvre les meilleurs talents du moment.', en: 'Short clips, vertical format. Swipe through videos and discover the best talents of the moment.', pt: 'Clips curtos, formato vertical. Faz swipe entre os vídeos e descobre os melhores talentos do momento.', es: 'Clips cortos, formato vertical. Desliza entre los videos y descubre a los mejores talentos del momento.', it: 'Clip brevi, formato verticale. Scorri tra i video e scopri i migliori talenti del momento.', de: 'Kurze Clips im Hochformat. Wische durch die Videos und entdecke die besten Talente des Moments.' },
  home_tiktok_football:     { fr: 'Le TikTok du Football',     en: 'The TikTok of Football', pt: 'O TikTok do Futebol',   es: 'El TikTok del Fútbol',   it: 'Il TikTok del Calcio',  de: 'Das TikTok des Fußballs' },
  home_voir_jogabonito:     { fr: 'Voir Jogabonito',           en: 'See Jogabonito',         pt: 'Ver Jogabonito',        es: 'Ver Jogabonito',         it: 'Vedi Jogabonito',       de: 'Jogabonito ansehen'   },
  // Composant HeroDashboardsPreview (src/components/) — nav des 3 profils +
  // phrase courte affichée sous le panneau actif.
  hero_preview_nav_joueur:    { fr: 'Joueur',    en: 'Player',  pt: 'Jogador',    es: 'Jugador',    it: 'Giocatore',  de: 'Spieler'  },
  hero_preview_nav_educateur: { fr: 'Éducateur', en: 'Coach',   pt: 'Treinador',  es: 'Entrenador',  it: 'Allenatore', de: 'Trainer'  },
  hero_preview_nav_club:      { fr: 'Club',      en: 'Club',    pt: 'Clube',      es: 'Club',        it: 'Club',       de: 'Verein'   },
  hero_preview_msg_joueur:    { fr: 'Suis ta progression. Développe ton potentiel.', en: 'Track your progress. Unlock your potential.', pt: 'Acompanha a tua evolução. Desenvolve o teu potencial.', es: 'Sigue tu progreso. Desarrolla tu potencial.', it: 'Segui i tuoi progressi. Sviluppa il tuo potenziale.', de: 'Verfolge deinen Fortschritt. Entfalte dein Potenzial.' },
  hero_preview_msg_educateur: { fr: "Prépare, organise et accompagne ton équipe.", en: 'Prepare, organize and support your team.', pt: 'Prepara, organiza e acompanha a tua equipa.', es: 'Prepara, organiza y acompaña a tu equipo.', it: 'Prepara, organizza e accompagna la tua squadra.', de: 'Bereite, organisiere und begleite dein Team.' },
  hero_preview_msg_club:      { fr: "Pilote ton club, du terrain à l'administration.", en: 'Run your club, from the pitch to admin.', pt: 'Gere o teu clube, do campo à administração.', es: 'Gestiona tu club, del campo a la administración.', it: "Gestisci il tuo club, dal campo all'amministrazione.", de: 'Führe deinen Verein, vom Platz bis zur Verwaltung.' },
  recrut_feed:          { fr: 'Feed',                  en: 'Feed',              pt: 'Feed',              es: 'Feed',              it: 'Feed',              de: 'Feed'              },
  // Section "Une plateforme. Trois univers." (Home.jsx, profilsCards) —
  // label (JOUEUR/ÉDUCATEUR/CLUB) réutilise hero_preview_nav_* ci-dessus
  // plutôt que de dupliquer la traduction.
  profils_section_titre:      { fr: 'Une plateforme. Trois univers.', en: 'One platform. Three worlds.', pt: 'Uma plataforma. Três universos.', es: 'Una plataforma. Tres universos.', it: 'Una piattaforma. Tre universi.', de: 'Eine Plattform. Drei Welten.' },
  profils_section_soustitre:  { fr: "Là où les autres outils s'adressent à un seul maillon, DigitalFootball crée de la valeur pour tous simultanément.", en: 'Where other tools serve a single link in the chain, DigitalFootball creates value for everyone at once.', pt: 'Onde outras ferramentas servem apenas um elo, a DigitalFootball cria valor para todos ao mesmo tempo.', es: 'Donde otras herramientas sirven a un solo eslabón, DigitalFootball crea valor para todos a la vez.', it: 'Dove altri strumenti servono un solo anello della catena, DigitalFootball crea valore per tutti insieme.', de: 'Wo andere Tools nur ein Glied bedienen, schafft DigitalFootball gleichzeitig Mehrwert für alle.' },
  profils_titre_joueur:       { fr: 'Progresse. Fais-toi remarquer.', en: 'Improve. Get noticed.', pt: 'Evolui. Faz-te notar.', es: 'Progresa. Hazte notar.', it: 'Migliora. Fatti notare.', de: 'Entwickle dich. Werde gesehen.' },
  profils_titre_educateur:    { fr: "Moins d'administratif. Plus de terrain.", en: 'Less admin. More pitch time.', pt: 'Menos administração. Mais campo.', es: 'Menos administración. Más terreno de juego.', it: 'Meno amministrazione. Più campo.', de: 'Weniger Verwaltung. Mehr Platz.' },
  profils_titre_club:         { fr: 'Un club mieux organisé, à tous les niveaux.', en: 'A better organized club, at every level.', pt: 'Um clube mais organizado, a todos os níveis.', es: 'Un club mejor organizado, a todos los niveles.', it: 'Un club meglio organizzato, a tutti i livelli.', de: 'Ein besser organisierter Verein, auf allen Ebenen.' },
  profils_desc_joueur:        { fr: 'Suis ton évolution, bénéficie des retours de ton éducateur et valorise ton profil auprès de la communauté football.', en: 'Track your progress, get feedback from your coach, and showcase your profile to the football community.', pt: 'Acompanha a tua evolução, recebe o feedback do teu treinador e valoriza o teu perfil junto da comunidade do futebol.', es: 'Sigue tu evolución, recibe el feedback de tu entrenador y da valor a tu perfil ante la comunidad del fútbol.', it: 'Segui la tua evoluzione, ricevi i feedback del tuo allenatore e valorizza il tuo profilo nella community del calcio.', de: 'Verfolge deine Entwicklung, erhalte Feedback von deinem Trainer und präsentiere dein Profil der Fußball-Community.' },
  profils_desc_educateur:     { fr: 'Prépare tes séances, organise ton équipe et accompagne la progression de tes joueurs depuis un seul espace.', en: 'Prepare your sessions, organize your team, and support your players\' progress from a single space.', pt: 'Prepara as tuas sessões, organiza a tua equipa e acompanha a evolução dos teus jogadores num único espaço.', es: 'Prepara tus sesiones, organiza tu equipo y acompaña el progreso de tus jugadores desde un solo espacio.', it: 'Prepara le tue sessioni, organizza la tua squadra e accompagna la crescita dei tuoi giocatori da un unico spazio.', de: 'Bereite deine Einheiten vor, organisiere dein Team und begleite die Entwicklung deiner Spieler an einem Ort.' },
  profils_desc_club:          { fr: 'Centralise la gestion sportive et administrative pour faciliter le quotidien de tes équipes et de tes dirigeants.', en: 'Centralize sporting and administrative management to make everyday life easier for your teams and officials.', pt: 'Centraliza a gestão desportiva e administrativa para facilitar o dia a dia das tuas equipas e dirigentes.', es: 'Centraliza la gestión deportiva y administrativa para facilitar el día a día de tus equipos y directivos.', it: 'Centralizza la gestione sportiva e amministrativa per semplificare la quotidianità di squadre e dirigenti.', de: 'Zentralisiere die sportliche und administrative Verwaltung für den Alltag deiner Teams und Vorstände.' },
  profils_feat_joueur_1:      { fr: 'Évaluations et suivi de progression', en: 'Evaluations & progress tracking', pt: 'Avaliações e acompanhamento de evolução', es: 'Evaluaciones y seguimiento de progreso', it: 'Valutazioni e monitoraggio dei progressi', de: 'Bewertungen & Fortschrittsverfolgung' },
  profils_feat_joueur_2:      { fr: 'Profil et visibilité sur la plateforme', en: 'Profile & visibility on the platform', pt: 'Perfil e visibilidade na plataforma', es: 'Perfil y visibilidad en la plataforma', it: 'Profilo e visibilità sulla piattaforma', de: 'Profil & Sichtbarkeit auf der Plattform' },
  profils_feat_joueur_3:      { fr: 'Analyses vidéo selon ton offre', en: 'Video analysis depending on your plan', pt: 'Análises de vídeo de acordo com o teu plano', es: 'Análisis de vídeo según tu plan', it: 'Analisi video in base al tuo piano', de: 'Videoanalysen je nach deinem Abo' },
  profils_feat_educateur_1:   { fr: 'Création et bibliothèque de séances', en: 'Session creation & drill library', pt: 'Criação e biblioteca de sessões', es: 'Creación y biblioteca de sesiones', it: 'Creazione e libreria di sessioni', de: 'Einheiten erstellen & Übungsbibliothek' },
  profils_feat_educateur_2:   { fr: 'Tacticboard interactif', en: 'Interactive tacticboard', pt: 'Quadro tático interativo', es: 'Pizarra táctica interactiva', it: 'Lavagna tattica interattiva', de: 'Interaktives Taktikboard' },
  profils_feat_educateur_3:   { fr: 'Présences et évaluations des joueurs', en: 'Attendance & player evaluations', pt: 'Presenças e avaliações de jogadores', es: 'Asistencia y evaluaciones de jugadores', it: 'Presenze e valutazioni giocatori', de: 'Anwesenheit & Spielerbewertungen' },
  profils_feat_club_1:        { fr: 'Planning des terrains et déplacements', en: 'Pitch scheduling & travel', pt: 'Calendário de campos e deslocações', es: 'Calendario de campos y desplazamientos', it: 'Pianificazione campi e trasferte', de: 'Platzbelegung & Fahrten' },
  profils_feat_club_2:        { fr: 'Coordination des équipes et du staff', en: 'Team & staff coordination', pt: 'Coordenação de equipas e staff', es: 'Coordinación de equipos y staff', it: 'Coordinamento squadre e staff', de: 'Team- & Staff-Koordination' },
  profils_feat_club_3:        { fr: 'Budget, sponsors et inventaire', en: 'Budget, sponsors & inventory', pt: 'Orçamento, patrocinadores e inventário', es: 'Presupuesto, patrocinadores e inventario', it: 'Budget, sponsor e inventario', de: 'Budget, Sponsoren & Inventar' },
  profils_cta_joueur:         { fr: 'Créer mon profil joueur', en: 'Create my player profile', pt: 'Criar o meu perfil de jogador', es: 'Crear mi perfil de jugador', it: 'Crea il mio profilo giocatore', de: 'Mein Spielerprofil erstellen' },
  profils_cta_educateur:      { fr: 'Découvrir les outils éducateur', en: 'Discover the coach tools', pt: 'Descobrir as ferramentas de treinador', es: 'Descubrir las herramientas de entrenador', it: 'Scopri gli strumenti allenatore', de: 'Trainer-Tools entdecken' },
  profils_cta_club:           { fr: 'Découvrir les solutions club', en: 'Discover the club solutions', pt: 'Descobrir as soluções para clubes', es: 'Descubrir las soluciones para clubes', it: 'Scopri le soluzioni club', de: 'Vereinslösungen entdecken' },
}

export const t = (key, lang = 'fr') => T_HOME[key]?.[lang] ?? T_HOME[key]?.['fr'] ?? key
